//! Upstream reference: types/context.ts
//!
//! The central type hub: the entity-typed [`InternalAdapter`] data API, the long-lived
//! [`AuthContext`], and the per-request [`GenericEndpointContext`]. These are mutually recursive
//! with `init-options.ts` (`BetterAuthOptions`), `plugin.ts` (`BetterAuthPlugin`) and `api/index.ts`
//! (`AuthMiddleware`), so they all land in one batch.
//!
//! ## Deviations from the TS (idiomatic + secure Rust)
//!
//! - **No `<Options>` generic.** Upstream threads `Options extends BetterAuthOptions` purely to
//!   drive compile-time plugin-id inference (`InferPluginID`, `BetterAuthPluginRegistry`); that
//!   inference has no runtime analog, so the Rust types are non-generic over a single concrete
//!   `BetterAuthOptions`.
//! - **No method generics.** TS `createUser<T>`/`updateUser<T>` returning `T & User` would break
//!   `dyn`-safety. We return the typed entity struct and carry plugin/extra columns in a
//!   [`WithExtra`] sidecar — see its docs.
//! - **`Option`, not exceptions, for "not found".** Upstream's `InternalAdapter` returns `null`
//!   (see `db/internal-adapter.ts`) and never throws `APIError`; the route layer mints those. So
//!   reads return `Option<T>` and fallible ops return [`InternalAdapterError`] (an infrastructure
//!   error wrapping the adapter / secondary-storage layers), mapped to `APIError` up in the routes.

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex};

use serde_json::{Map, Value};
use time::{Duration, OffsetDateTime};

use crate::db::adapter::{DatabaseAdapter, SortBy, Where};
use crate::db::schema::{Account, Session, User, Verification};
use crate::db::{AdapterError, BetterAuthDbSchema, SecondaryStorage, SecondaryStorageError};
use crate::env::logger::InternalLogger;
use crate::oauth2::DynOAuthProvider;
use crate::types::cookie::BetterAuthCookies;
use crate::types::init_options::{
    BackgroundTaskHandler, BetterAuthOptions, BetterAuthRateLimitStorage, BoxFuture,
    CustomRateLimitRule, GenerateIdConfig, GenerateIdInput, RateLimitStorageKind,
};
use crate::types::plugin::BetterAuthPlugin;
use crate::types::secret::SecretConfig;

/// An infrastructure error from an [`InternalAdapter`] operation.
///
/// The `InternalAdapter` is a thin, entity-typed layer over the dynamic
/// [`DatabaseAdapter`](crate::db::adapter::DatabaseAdapter): "not found" is modeled as `Option`, so
/// this error channel carries only genuine backend failures (the underlying adapter or secondary
/// storage). Routes map it to an `APIError` (a 500-class response); the domain `APIError`s
/// (`USER_NOT_FOUND`, `FAILED_TO_CREATE_USER`, …) are minted by the routes, not here — matching the
/// upstream implementation, which imports no error types and returns `null` for absence.
#[derive(Debug, thiserror::Error)]
pub enum InternalAdapterError {
    /// An error from the underlying database adapter.
    #[error(transparent)]
    Adapter(#[from] AdapterError),
    /// An error from the configured secondary storage.
    #[error(transparent)]
    SecondaryStorage(#[from] SecondaryStorageError),
}

/// Result alias for [`InternalAdapter`] operations.
pub type InternalAdapterResult<T> = Result<T, InternalAdapterError>;

/// A typed entity plus the extra (plugin/option-added) columns that rode alongside it.
///
/// Upstream types create/update returns as `Entity & T` where `T` is the open
/// `Record<string, any>` of plugin-added fields. Rust has no runtime analog for that intersection,
/// and a method generic would break trait-object safety, so we return the typed `record` plus an
/// `extra` map of the columns outside the base schema. Callers that only need the base entity read
/// `record`; plugin code reads `extra`.
#[derive(Debug, Clone)]
pub struct WithExtra<R> {
    /// The typed base entity.
    pub record: R,
    /// Columns outside the base schema (plugin/option-added fields).
    pub extra: Map<String, Value>,
}

/// Input for creating a user (`createUser` / the user half of `createOAuthUser`).
///
/// Mirrors `Omit<User, "id" | "createdAt" | "updatedAt"> & Partial<User> & Record`: the id and
/// timestamps are generated by the adapter, `email_verified` is optional (defaults to `false` for
/// credential signup, set by the OAuth flow), and `extra` carries plugin-added columns.
#[derive(Debug, Clone, Default)]
pub struct NewUser {
    /// Email address (normalized to lowercase on insert).
    pub email: String,
    /// Display name.
    pub name: String,
    /// Optional avatar URL.
    pub image: Option<String>,
    /// Whether the email is already verified (defaults to `false`).
    pub email_verified: Option<bool>,
    /// Plugin/option-added columns.
    pub extra: Map<String, Value>,
}

/// Input for creating/linking an account (`createAccount` / `linkAccount`).
///
/// Mirrors `Omit<Account, "id" | "createdAt" | "updatedAt"> & Partial<Account>`.
#[derive(Debug, Clone, Default)]
pub struct NewAccount {
    /// Provider id (e.g. `"google"`, `"credential"`).
    pub provider_id: String,
    /// The account id at the provider.
    pub account_id: String,
    /// The owning user's id.
    pub user_id: String,
    /// OAuth access token.
    pub access_token: Option<String>,
    /// OAuth refresh token.
    pub refresh_token: Option<String>,
    /// OIDC id token.
    pub id_token: Option<String>,
    /// Access-token expiry.
    pub access_token_expires_at: Option<OffsetDateTime>,
    /// Refresh-token expiry.
    pub refresh_token_expires_at: Option<OffsetDateTime>,
    /// Authorized scopes.
    pub scope: Option<String>,
    /// Hashed password (credential provider only).
    pub password: Option<String>,
    /// Plugin/option-added columns.
    pub extra: Map<String, Value>,
}

/// Input for the account half of `createOAuthUser`.
///
/// Mirrors `Omit<Account, "userId" | "id" | "createdAt" | "updatedAt"> & Partial<Account>`: the
/// `user_id` is filled in by the method from the freshly-created user, so it is absent here.
#[derive(Debug, Clone, Default)]
pub struct NewOAuthAccount {
    /// Provider id.
    pub provider_id: String,
    /// The account id at the provider.
    pub account_id: String,
    /// OAuth access token.
    pub access_token: Option<String>,
    /// OAuth refresh token.
    pub refresh_token: Option<String>,
    /// OIDC id token.
    pub id_token: Option<String>,
    /// Access-token expiry.
    pub access_token_expires_at: Option<OffsetDateTime>,
    /// Refresh-token expiry.
    pub refresh_token_expires_at: Option<OffsetDateTime>,
    /// Authorized scopes.
    pub scope: Option<String>,
    /// Plugin/option-added columns.
    pub extra: Map<String, Value>,
}

/// Partial user update (`Partial<User> & Record`).
///
/// `Some` updates the column, `None` leaves it. For nullable columns, `Some(None)` clears the
/// column to null while `Some(Some(v))` sets it — distinguishing "set null" from "leave".
#[derive(Debug, Clone, Default)]
pub struct UserUpdate {
    /// Update the email.
    pub email: Option<String>,
    /// Update the display name.
    pub name: Option<String>,
    /// Update the avatar URL (`Some(None)` clears it).
    pub image: Option<Option<String>>,
    /// Update the verified flag.
    pub email_verified: Option<bool>,
    /// Plugin/option-added columns to update.
    pub extra: Map<String, Value>,
}

/// Partial session update (`Partial<Session> & Record`); also `createSession`'s override.
#[derive(Debug, Clone, Default)]
pub struct SessionUpdate {
    /// Update the owning user id.
    pub user_id: Option<String>,
    /// Update the expiry.
    pub expires_at: Option<OffsetDateTime>,
    /// Update the token.
    pub token: Option<String>,
    /// Update the IP address (`Some(None)` clears it).
    pub ip_address: Option<Option<String>>,
    /// Update the user agent (`Some(None)` clears it).
    pub user_agent: Option<Option<String>>,
    /// Plugin/option-added columns to update.
    pub extra: Map<String, Value>,
}

/// Partial account update (`Partial<Account>`).
#[derive(Debug, Clone, Default)]
pub struct AccountUpdate {
    /// Update the provider id.
    pub provider_id: Option<String>,
    /// Update the provider's account id.
    pub account_id: Option<String>,
    /// Update the owning user id.
    pub user_id: Option<String>,
    /// Update the access token (`Some(None)` clears it).
    pub access_token: Option<Option<String>>,
    /// Update the refresh token (`Some(None)` clears it).
    pub refresh_token: Option<Option<String>>,
    /// Update the id token (`Some(None)` clears it).
    pub id_token: Option<Option<String>>,
    /// Update the access-token expiry (`Some(None)` clears it).
    pub access_token_expires_at: Option<Option<OffsetDateTime>>,
    /// Update the refresh-token expiry (`Some(None)` clears it).
    pub refresh_token_expires_at: Option<Option<OffsetDateTime>>,
    /// Update the scope (`Some(None)` clears it).
    pub scope: Option<Option<String>>,
    /// Update the hashed password (`Some(None)` clears it).
    pub password: Option<Option<String>>,
    /// Plugin/option-added columns to update.
    pub extra: Map<String, Value>,
}

/// Partial verification update (`Partial<Verification>`).
#[derive(Debug, Clone, Default)]
pub struct VerificationUpdate {
    /// Update the stored value.
    pub value: Option<String>,
    /// Update the expiry.
    pub expires_at: Option<OffsetDateTime>,
    /// Update the identifier.
    pub identifier: Option<String>,
    /// Plugin/option-added columns to update.
    pub extra: Map<String, Value>,
}

/// Input for `createVerificationValue`.
///
/// Mirrors `Omit<Verification, "createdAt" | "id" | "updatedAt"> & Partial<Verification>`: `id` is
/// an optional override (otherwise generated).
#[derive(Debug, Clone)]
pub struct NewVerification {
    /// The identifier the value is keyed by.
    pub identifier: String,
    /// The stored value (token/code).
    pub value: String,
    /// When the value expires.
    pub expires_at: OffsetDateTime,
    /// Optional id override (otherwise adapter-generated).
    pub id: Option<String>,
    /// Plugin/option-added columns.
    pub extra: Map<String, Value>,
}

/// Input for [`InternalAdapter::reserve_verification_value`].
#[derive(Debug, Clone)]
pub struct ReserveVerification {
    /// The identifier to reserve (derives the deterministic primary key).
    pub identifier: String,
    /// The value to store on first write.
    pub value: String,
    /// When the reservation expires.
    pub expires_at: OffsetDateTime,
}

/// Options for `listSessions` / `findSessions`.
#[derive(Debug, Clone, Copy, Default)]
pub struct ListSessionsOptions {
    /// Exclude sessions whose `expires_at` is in the past.
    pub only_active_sessions: bool,
}

/// Options for `listUsers` (limit / offset / sort / filter).
#[derive(Debug, Clone, Default)]
pub struct ListUsersOptions {
    /// Max rows to return.
    pub limit: Option<u64>,
    /// Rows to skip.
    pub offset: Option<u64>,
    /// Sort order.
    pub sort_by: Option<SortBy>,
    /// Filter conditions (empty = no filter).
    pub conditions: Vec<Where>,
}

/// Options for `findUserByEmail`.
#[derive(Debug, Clone, Copy, Default)]
pub struct FindUserByEmailOptions {
    /// Also load the user's accounts.
    pub include_accounts: bool,
}

/// Options for `createSession`.
#[derive(Debug, Clone, Default)]
pub struct CreateSessionOptions {
    /// Whether the session is non-persistent ("don't remember me").
    pub dont_remember_me: bool,
    /// Fields to override on the created session (`Partial<Session> & Record`).
    pub override_fields: Option<SessionUpdate>,
    /// Override every field (not just the provided ones).
    pub override_all: bool,
}

/// A session paired with its user (the `{ session, user }` shape).
#[derive(Debug, Clone)]
pub struct SessionWithUser {
    /// The session.
    pub session: Session,
    /// The owning user.
    pub user: User,
}

/// Return of `findOAuthUser`.
#[derive(Debug, Clone)]
pub struct OAuthUserResult {
    /// The matched user.
    pub user: User,
    /// The account linked to the queried provider, if any.
    pub linked_account: Option<Account>,
    /// All of the user's accounts.
    pub accounts: Vec<Account>,
}

/// Return of `findUserByEmail`.
#[derive(Debug, Clone)]
pub struct UserWithAccounts {
    /// The matched user.
    pub user: User,
    /// The user's accounts (empty unless `include_accounts` was set).
    pub accounts: Vec<Account>,
}

/// Return of `createOAuthUser`.
#[derive(Debug, Clone)]
pub struct OAuthUserCreated {
    /// The created user.
    pub user: User,
    /// The created account.
    pub account: Account,
}

/// The entity-typed data API layered over the dynamic
/// [`DatabaseAdapter`](crate::db::adapter::DatabaseAdapter) (`InternalAdapter` in `context.ts`).
///
/// Held by [`AuthContext`](crate::types::context::AuthContext) as `Arc<dyn InternalAdapter>`. This
/// is the **contract**; the concrete implementation (`create_internal_adapter`, which wires hooks,
/// transforms, id generation and secondary storage over the adapter) is a separate, later batch.
/// Defining the trait now lets the routes layer and tests code against — and mock — the interface.
#[async_trait::async_trait]
pub trait InternalAdapter: Send + Sync {
    // ── users ────────────────────────────────────────────────────────────────

    /// Create a user and a linked account in one operation (`createOAuthUser`).
    async fn create_oauth_user(
        &self,
        user: NewUser,
        account: NewOAuthAccount,
    ) -> InternalAdapterResult<OAuthUserCreated>;

    /// Create a user (`createUser`). Plugin/extra columns ride back in [`WithExtra::extra`].
    async fn create_user(&self, user: NewUser) -> InternalAdapterResult<WithExtra<User>>;

    /// List users with optional paging, sort, and filter (`listUsers`).
    async fn list_users(&self, options: ListUsersOptions) -> InternalAdapterResult<Vec<User>>;

    /// Count users matching the conditions (`countTotalUsers`).
    async fn count_total_users(&self, conditions: Vec<Where>) -> InternalAdapterResult<u64>;

    /// Find a user by email, optionally with their accounts (`findUserByEmail`).
    async fn find_user_by_email(
        &self,
        email: &str,
        options: FindUserByEmailOptions,
    ) -> InternalAdapterResult<Option<UserWithAccounts>>;

    /// Find a user by id (`findUserById`).
    async fn find_user_by_id(&self, user_id: &str) -> InternalAdapterResult<Option<User>>;

    /// Update a user by id (`updateUser`). Plugin/extra columns ride back in [`WithExtra::extra`].
    async fn update_user(
        &self,
        user_id: &str,
        data: UserUpdate,
    ) -> InternalAdapterResult<WithExtra<User>>;

    /// Update a user by email (`updateUserByEmail`).
    async fn update_user_by_email(
        &self,
        email: &str,
        data: UserUpdate,
    ) -> InternalAdapterResult<WithExtra<User>>;

    /// Set a user's credential password (`updatePassword`).
    async fn update_password(&self, user_id: &str, password: &str) -> InternalAdapterResult<()>;

    /// Delete a user (`deleteUser`).
    async fn delete_user(&self, user_id: &str) -> InternalAdapterResult<()>;

    /// Bump every session of a user so caches/refreshes re-read the latest user (`refreshUserSessions`).
    async fn refresh_user_sessions(&self, user: &User) -> InternalAdapterResult<()>;

    // ── accounts ─────────────────────────────────────────────────────────────

    /// Create an account (`createAccount`). Plugin/extra columns ride back in [`WithExtra::extra`].
    async fn create_account(
        &self,
        account: NewAccount,
    ) -> InternalAdapterResult<WithExtra<Account>>;

    /// Link an account to an existing user (`linkAccount`).
    async fn link_account(&self, account: NewAccount) -> InternalAdapterResult<Account>;

    /// All accounts owned by a user (`findAccounts`).
    async fn find_accounts(&self, user_id: &str) -> InternalAdapterResult<Vec<Account>>;

    /// Find an account by its provider-side account id + provider id (`findAccountByProviderId`).
    async fn find_account_by_provider_id(
        &self,
        account_id: &str,
        provider_id: &str,
    ) -> InternalAdapterResult<Option<Account>>;

    /// All accounts owned by a user, by user id (`findAccountByUserId`).
    async fn find_account_by_user_id(&self, user_id: &str) -> InternalAdapterResult<Vec<Account>>;

    /// Find a user (and their accounts) for an OAuth sign-in (`findOAuthUser`).
    async fn find_oauth_user(
        &self,
        email: &str,
        account_id: &str,
        provider_id: &str,
    ) -> InternalAdapterResult<Option<OAuthUserResult>>;

    /// Update an account by its primary key (`updateAccount`).
    async fn update_account(&self, id: &str, data: AccountUpdate)
    -> InternalAdapterResult<Account>;

    /// Delete an account by its primary key — the `id` column, not the `accountId` column
    /// (`deleteAccount`).
    async fn delete_account(&self, id: &str) -> InternalAdapterResult<()>;

    /// Delete every account belonging to a user (`deleteAccounts`).
    async fn delete_accounts(&self, user_id: &str) -> InternalAdapterResult<()>;

    // ── sessions ─────────────────────────────────────────────────────────────

    /// Create a session for a user (`createSession`).
    async fn create_session(
        &self,
        user_id: &str,
        options: CreateSessionOptions,
    ) -> InternalAdapterResult<Session>;

    /// List a user's sessions (`listSessions`).
    async fn list_sessions(
        &self,
        user_id: &str,
        options: ListSessionsOptions,
    ) -> InternalAdapterResult<Vec<Session>>;

    /// Resolve a session token to its session + user (`findSession`).
    async fn find_session(&self, token: &str) -> InternalAdapterResult<Option<SessionWithUser>>;

    /// Resolve many session tokens to session + user pairs (`findSessions`).
    async fn find_sessions(
        &self,
        session_tokens: &[String],
        options: ListSessionsOptions,
    ) -> InternalAdapterResult<Vec<SessionWithUser>>;

    /// Update a session by its token (`updateSession`). Returns `None` if no session matched.
    async fn update_session(
        &self,
        session_token: &str,
        session: SessionUpdate,
    ) -> InternalAdapterResult<Option<Session>>;

    /// Delete a session by its token (`deleteSession`).
    async fn delete_session(&self, token: &str) -> InternalAdapterResult<()>;

    /// Delete every session belonging to a user (`deleteUserSessions`).
    async fn delete_user_sessions(&self, user_id: &str) -> InternalAdapterResult<()>;

    /// Delete sessions by their tokens (`deleteSessions`).
    async fn delete_sessions(&self, session_tokens: &[String]) -> InternalAdapterResult<()>;

    // ── verification ───────────────────────────────────────────────────────

    /// Create a verification row (`createVerificationValue`).
    async fn create_verification_value(
        &self,
        data: NewVerification,
    ) -> InternalAdapterResult<Verification>;

    /// Find the verification row for an identifier (`findVerificationValue`). Returns the latest.
    async fn find_verification_value(
        &self,
        identifier: &str,
    ) -> InternalAdapterResult<Option<Verification>>;

    /// Update verification rows by identifier (`updateVerificationByIdentifier`).
    async fn update_verification_by_identifier(
        &self,
        identifier: &str,
        data: VerificationUpdate,
    ) -> InternalAdapterResult<Verification>;

    /// Delete verification rows by identifier (`deleteVerificationByIdentifier`).
    async fn delete_verification_by_identifier(
        &self,
        identifier: &str,
    ) -> InternalAdapterResult<()>;

    /// Atomically consume a single-use verification row by `identifier` and return it
    /// (`consumeVerificationValue`).
    ///
    /// Only the first concurrent caller receives the latest row; subsequent callers receive `None`.
    /// Consuming one row invalidates the whole identifier so stale rows cannot be replayed. Rows
    /// past their `expires_at` are treated as already invalid: the row is deleted but `None` is
    /// returned, so callers do not need to gate on `expires_at` themselves. **Callers MUST gate any
    /// state change (issue session, mint token, change password) on a non-`None` result.**
    ///
    /// Replaces the racy `find_verification_value` + `delete_verification_by_identifier` pair at
    /// single-use credential consumption sites.
    async fn consume_verification_value(
        &self,
        identifier: &str,
    ) -> InternalAdapterResult<Option<Verification>>;

    /// First-writer-wins create keyed by a deterministic primary key derived from `identifier`
    /// (`reserveVerificationValue`). Returns `true` when this caller created the row and `false`
    /// when a row for the same identifier already existed.
    ///
    /// The dual of [`consume_verification_value`](Self::consume_verification_value): reserve races
    /// to create a marker exactly once, where consume races to delete one exactly once. Use it for
    /// replay tombstones (a SAML assertion id, a JWT `jti`) where the first caller wins. The
    /// database path is atomic via the primary key; the secondary-storage-only path is best-effort
    /// under concurrency.
    async fn reserve_verification_value(
        &self,
        data: ReserveVerification,
    ) -> InternalAdapterResult<bool>;
}

// ─────────────────────────────────────────────────────────────────────────────
// AuthContext — the long-lived, immutable, Arc-shared application context.
// ─────────────────────────────────────────────────────────────────────────────

/// Strategy for storing OAuth `state` (`oauthConfig.storeStateStrategy`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum StoreStateStrategy {
    /// Store state in the database (the default when a database/secondary storage is configured).
    #[default]
    Database,
    /// Store state in an encrypted cookie (stateless).
    Cookie,
}

/// Resolved OAuth configuration (`oauthConfig`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct OAuthConfig {
    /// Skip the OAuth state-cookie check (dangerous; dev/staging only).
    pub skip_state_cookie_check: bool,
    /// How OAuth `state` is stored.
    pub store_state_strategy: StoreStateStrategy,
}

/// Stateless cookie-cache refresh policy (`sessionConfig.cookieRefreshCache`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CookieRefreshCache {
    /// No automatic refresh (the default; `false`).
    #[default]
    Disabled,
    /// Refresh the cookie cache `update_age` before expiry, without a database read.
    Enabled {
        /// Seconds before expiry at which to refresh.
        update_age: Duration,
    },
}

/// Resolved session configuration (`sessionConfig`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SessionConfig {
    /// How often a session is refreshed.
    pub update_age: Duration,
    /// How long a session lives.
    pub expires_in: Duration,
    /// How recently a session must have been created to count as "fresh" for sensitive operations.
    pub fresh_age: Duration,
    /// Stateless cookie-cache refresh policy.
    pub cookie_refresh_cache: CookieRefreshCache,
}

/// The signing/encryption secret source (`secret` / `secretConfig`): a single secret or a rotating
/// set. Secret material is never logged (redacting [`Debug`]).
#[derive(Clone)]
pub enum SecretSource {
    /// A single secret.
    Single(String),
    /// A versioned, rotating set of secrets.
    Rotating(SecretConfig),
}

impl core::fmt::Debug for SecretSource {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Single(_) => f.write_str("Single(<redacted>)"),
            Self::Rotating(c) => f.debug_tuple("Rotating").field(c).finish(),
        }
    }
}

/// Whether to skip the request origin check (`skipOriginCheck`): for all requests, for specific
/// path prefixes, or never. Upstream's `boolean | string[]` as a closed enum.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum SkipOriginCheck {
    /// Skip for ALL requests (dangerous — disables CSRF protection).
    All,
    /// Skip only for requests whose path matches one of these prefixes (e.g. SAML callbacks).
    Paths(Vec<String>),
    /// Enforce the origin check (the default).
    #[default]
    None,
}

/// Input to a [`PasswordVerifyFn`].
#[derive(Debug, Clone)]
pub struct PasswordVerifyInput {
    /// The plaintext password being checked.
    pub password: String,
    /// The stored hash to verify against.
    pub hash: String,
}

/// Resolved password length policy (`password.config`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PasswordConfig {
    /// Minimum acceptable password length.
    pub min_password_length: usize,
    /// Maximum acceptable password length.
    pub max_password_length: usize,
}

/// Hash a password (`password.hash`). Overridable via `options.emailAndPassword.password.hash`.
pub type PasswordHashFn =
    Arc<dyn Fn(String) -> BoxFuture<Result<String, CallbackError>> + Send + Sync>;

/// Verify a password against a hash (`password.verify`).
pub type PasswordVerifyFn =
    Arc<dyn Fn(PasswordVerifyInput) -> BoxFuture<Result<bool, CallbackError>> + Send + Sync>;

/// A boxed error from a context closure (password hashing, telemetry, …).
pub type CallbackError = Box<dyn std::error::Error + Send + Sync>;

/// Password machinery resolved onto the context (`password`).
///
/// `hash`/`verify` are stored closures because they are user-overridable (defaulting to the
/// argon2id helpers in `better-auth-rs-utils`). `checkPassword` is intentionally **not** here: it
/// needs the request body and the adapter and lands with the password/request layer.
#[derive(Clone)]
pub struct PasswordContext {
    /// The hashing function.
    pub hash: PasswordHashFn,
    /// The verification function.
    pub verify: PasswordVerifyFn,
    /// The length policy.
    pub config: PasswordConfig,
}

impl core::fmt::Debug for PasswordContext {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("PasswordContext")
            .field("hash", &"<fn>")
            .field("verify", &"<fn>")
            .field("config", &self.config)
            .finish()
    }
}

/// A telemetry event (`publishTelemetry`'s argument).
#[derive(Debug, Clone)]
pub struct TelemetryEvent {
    /// The event type.
    pub event_type: String,
    /// An optional anonymous id.
    pub anonymous_id: Option<String>,
    /// The event payload.
    pub payload: Value,
}

/// Publish a telemetry event (`publishTelemetry`).
pub type TelemetryPublishFn = Arc<dyn Fn(TelemetryEvent) -> BoxFuture<()> + Send + Sync>;

/// Resolved rate-limit configuration carried on the context (`rateLimit`).
///
/// Unlike [`BetterAuthRateLimitOptions`](crate::types::init_options::BetterAuthRateLimitOptions)
/// (where everything is optional), the enabled/window/max/storage values are resolved here.
#[derive(Clone)]
pub struct ResolvedRateLimit {
    /// Whether rate limiting is enabled.
    pub enabled: bool,
    /// Default window, in seconds.
    pub window: u64,
    /// Default max requests per window.
    pub max: u64,
    /// Where counters are stored.
    pub storage: RateLimitStorageKind,
    /// Override the rate-limit table name.
    pub model_name: Option<String>,
    /// Map rate-limit fields to columns.
    pub fields: Option<BTreeMap<String, String>>,
    /// Custom rules per path: apply a rule or exempt the path.
    pub custom_rules: Option<BTreeMap<String, CustomRateLimitRule>>,
    /// Custom storage backend (overrides `storage`).
    pub custom_storage: Option<Arc<dyn BetterAuthRateLimitStorage>>,
}

impl core::fmt::Debug for ResolvedRateLimit {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("ResolvedRateLimit")
            .field("enabled", &self.enabled)
            .field("window", &self.window)
            .field("max", &self.max)
            .field("storage", &self.storage)
            .field("model_name", &self.model_name)
            .field("fields", &self.fields)
            .field("custom_rules", &self.custom_rules)
            .field(
                "custom_storage",
                &self.custom_storage.as_ref().map(|_| "<storage>"),
            )
            .finish()
    }
}

/// Settings for [`AuthContext::is_trusted_origin`] (`isTrustedOrigin`'s `settings`).
#[derive(Debug, Clone, Copy, Default)]
pub struct TrustedOriginMatch {
    /// Whether to treat same-origin relative paths (`/foo`) as trusted.
    pub allow_relative_paths: bool,
}

/// The long-lived application context (`AuthContext`).
///
/// Built once at startup (by the published crate's `create_auth_context`) and shared as
/// `Arc<AuthContext>` across every concurrent request. It is **deeply immutable**: it holds only
/// resolved config, `Arc<dyn …>` trait objects, and stored closures, and exposes behavior as
/// `&self` methods. Request-scoped mutable state (the session being set on the response) lives on
/// the per-request [`GenericEndpointContext`], never here — so two concurrent requests can never
/// observe or clobber each other's session.
///
/// Deviation from the TS `AuthContext`: it is non-generic (the `<Options>` plugin-id inference is
/// compile-time only), the request-scoped `newSession`/`session`/`setNewSession` move to
/// [`GenericEndpointContext`], and the `context/` AsyncLocalStorage machinery is replaced by
/// threading `&AuthContext` / `Arc<AuthContext>` explicitly.
///
/// ## Methods that land with later batches (fields are present so they slot in without a reshape)
///
/// - `is_trusted_origin` — the wildcard origin matcher is security-critical and ports with the
///   dedicated origin-matching util (with its own tests); the `trusted_origins` field is here now.
/// - `create_auth_cookie` — the `__Host-`/`__Secure-` prefixing logic ports with the cookies layer.
/// - `check_password` — needs the request body + adapter; ports with the password/request layer.
/// - `run_migrations` — injected by the published-crate init layer.
pub struct AuthContext {
    /// Application display name (`appName`).
    pub app_name: String,
    /// The resolved server root URL (`baseURL`).
    pub base_url: String,
    /// The library/app version (`version`).
    pub version: String,
    /// The full configuration (`options`). Behavior methods read resolved fields below, not this.
    pub options: BetterAuthOptions,
    /// Resolved trusted origins (`trustedOrigins`).
    pub trusted_origins: Vec<String>,
    /// Resolved trusted providers for account linking (`trustedProviders`).
    pub trusted_providers: Vec<String>,
    /// Resolved OAuth configuration (`oauthConfig`).
    pub oauth_config: OAuthConfig,
    /// Instantiated social providers (`socialProviders`).
    pub social_providers: Vec<DynOAuthProvider>,
    /// The managed cookie set (`authCookies`).
    pub auth_cookies: BetterAuthCookies,
    /// The logger (`logger`).
    pub logger: Arc<InternalLogger>,
    /// Resolved rate-limit configuration (`rateLimit`).
    pub rate_limit: ResolvedRateLimit,
    /// The active database adapter (`adapter`).
    pub adapter: Arc<dyn DatabaseAdapter>,
    /// The entity-typed data API over the adapter (`internalAdapter`).
    pub internal_adapter: Arc<dyn InternalAdapter>,
    /// The primary secret (`secret`). Never logged.
    pub secret: String,
    /// The secret source for rotation (`secretConfig`). Never logged.
    pub secret_config: SecretSource,
    /// Resolved session configuration (`sessionConfig`).
    pub session_config: SessionConfig,
    /// How ids are generated (`generateId`'s backing config).
    pub generate_id: GenerateIdConfig,
    /// Optional secondary storage (`secondaryStorage`).
    pub secondary_storage: Option<Arc<dyn SecondaryStorage>>,
    /// Password machinery (`password`).
    pub password: PasswordContext,
    /// The resolved table schema, with plugin extensions (`tables`).
    pub tables: BetterAuthDbSchema,
    /// Whether to skip the origin check (`skipOriginCheck`).
    pub skip_origin_check: SkipOriginCheck,
    /// Whether to skip the CSRF check (`skipCSRFCheck`).
    pub skip_csrf_check: bool,
    /// Telemetry sink (`publishTelemetry`), if configured.
    pub publish_telemetry: Option<TelemetryPublishFn>,
    /// Background-task handler (`advanced.backgroundTasks.handler`), if configured.
    pub background_tasks: Option<BackgroundTaskHandler>,
}

impl AuthContext {
    /// Find a loaded plugin by id (`getPlugin`). Returns `None` if no plugin has that id.
    ///
    /// The TS generic return-type narrowing has no runtime analog; this returns the trait object,
    /// which callers may downcast if they need a concrete plugin.
    #[must_use]
    pub fn get_plugin(&self, id: &str) -> Option<Arc<dyn BetterAuthPlugin>> {
        self.options.plugins.iter().find(|p| p.id() == id).cloned()
    }

    /// Whether a plugin with the given id is loaded (`hasPlugin`).
    #[must_use]
    pub fn has_plugin(&self, id: &str) -> bool {
        self.options.plugins.iter().any(|p| p.id() == id)
    }

    /// Generate an id for `model` (`generateId`). Returns `None` when the database/adapter should
    /// generate the id itself (the upstream `false`).
    ///
    /// `Uuid`/`Serial`/`Database` defer to the adapter (it knows the dialect's id mechanism);
    /// `Default` uses the crate's random id generator; `Custom` calls the user's function.
    #[must_use]
    pub fn generate_id(&self, model: &str, size: Option<usize>) -> Option<String> {
        match &self.generate_id {
            GenerateIdConfig::Default => Some(crate::utils::generate_id(size)),
            GenerateIdConfig::Database | GenerateIdConfig::Serial | GenerateIdConfig::Uuid => None,
            GenerateIdConfig::Custom(f) => f(GenerateIdInput {
                model: model.to_owned(),
                size,
            }),
        }
    }

    /// Run a future in the background if a handler is configured, otherwise await it inline
    /// (`runInBackgroundOrAwait`).
    ///
    /// Core depends on no async runtime, so it cannot spawn on its own — the configured
    /// [`BackgroundTaskHandler`] is the injection seam (e.g. Vercel `waitUntil`). Without one, the
    /// future is awaited inline so the work is never silently dropped. The fire-and-forget
    /// `runInBackground` (which needs a runtime to spawn) lands in the published crate.
    pub async fn run_in_background_or_await(&self, fut: BoxFuture<()>) {
        match &self.background_tasks {
            Some(handler) => handler(fut),
            None => fut.await,
        }
    }
}

impl core::fmt::Debug for AuthContext {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("AuthContext")
            .field("app_name", &self.app_name)
            .field("base_url", &self.base_url)
            .field("version", &self.version)
            .field("options", &self.options)
            .field("trusted_origins", &self.trusted_origins)
            .field("trusted_providers", &self.trusted_providers)
            .field("oauth_config", &self.oauth_config)
            .field(
                "social_providers",
                &format_args!("[{} provider(s)]", self.social_providers.len()),
            )
            .field("auth_cookies", &self.auth_cookies)
            .field("logger", &"<logger>")
            .field("rate_limit", &self.rate_limit)
            .field(
                "adapter",
                &format_args!("<dyn DatabaseAdapter: {}>", self.adapter.id()),
            )
            .field("internal_adapter", &"<dyn InternalAdapter>")
            .field("secret", &"<redacted>")
            .field("secret_config", &self.secret_config)
            .field("session_config", &self.session_config)
            .field("generate_id", &self.generate_id)
            .field(
                "secondary_storage",
                &self
                    .secondary_storage
                    .as_ref()
                    .map(|_| "<dyn SecondaryStorage>"),
            )
            .field("password", &self.password)
            .field("tables", &format_args!("[{} table(s)]", self.tables.len()))
            .field("skip_origin_check", &self.skip_origin_check)
            .field("skip_csrf_check", &self.skip_csrf_check)
            .field(
                "publish_telemetry",
                &self.publish_telemetry.as_ref().map(|_| "<fn>"),
            )
            .field(
                "background_tasks",
                &self.background_tasks.as_ref().map(|_| "<fn>"),
            )
            .finish()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// GenericEndpointContext — the per-request context.
// ─────────────────────────────────────────────────────────────────────────────

/// Per-request session state mutated over the course of a request.
#[derive(Debug, Default)]
struct RequestSessionState {
    /// The session resolved for the current request (`session`).
    session: Option<SessionWithUser>,
    /// The session to set on the response via `Set-Cookie` (`newSession`).
    new_session: Option<SessionWithUser>,
}

/// The per-request context (`GenericEndpointContext`).
///
/// Holds an `Arc<AuthContext>` (a cheap clone of the shared app context) plus the request-scoped
/// session state. The session state lives behind a [`Mutex`] so the context can be shared as
/// `Arc<GenericEndpointContext>` into async lifecycle callbacks and database hooks while still being
/// mutated via `&self`. The mutex is safe here precisely because this object is **per request** —
/// it is never shared across requests, so there is no cross-request session bleed (the property the
/// immutable [`AuthContext`] split guarantees).
///
/// The request/response half (headers, method, path, body) is populated by the api/integration
/// layer in a later batch.
pub struct GenericEndpointContext {
    /// The shared application context.
    pub context: Arc<AuthContext>,
    session: Mutex<RequestSessionState>,
}

impl GenericEndpointContext {
    /// Create a per-request context wrapping the shared [`AuthContext`].
    #[must_use]
    pub fn new(context: Arc<AuthContext>) -> Self {
        Self {
            context,
            session: Mutex::new(RequestSessionState::default()),
        }
    }

    fn lock(&self) -> std::sync::MutexGuard<'_, RequestSessionState> {
        // Poison-tolerant: a panic in one request's handler must not wedge the per-request state.
        self.session
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
    }

    /// The session resolved for the current request, if any (`session`).
    #[must_use]
    pub fn session(&self) -> Option<SessionWithUser> {
        self.lock().session.clone()
    }

    /// Set the session resolved for the current request.
    pub fn set_session(&self, session: Option<SessionWithUser>) {
        self.lock().session = session;
    }

    /// The session queued to be written to the response (`newSession`).
    #[must_use]
    pub fn new_session(&self) -> Option<SessionWithUser> {
        self.lock().new_session.clone()
    }

    /// Queue a session to be written to the response via `Set-Cookie` (`setNewSession`).
    pub fn set_new_session(&self, session: Option<SessionWithUser>) {
        self.lock().new_session = session;
    }
}

impl core::fmt::Debug for GenericEndpointContext {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("GenericEndpointContext")
            .field("context", &self.context)
            .field("session", &self.lock())
            .finish()
    }
}

#[cfg(test)]
#[path = "context.test.rs"]
mod context_tests;
